### ISSUE TITLE
Error fetching JIRA issue

### ISSUE THREAD

**Issue by jsandova** [esigler/lita-jira#16]
I have installed the gem "lita-jira" and am getting the following error when attempting to query a JIRA ticket. 

!jira it-1651
Error fetching JIRA issue

If I run a JIRA api command via curl I am able to query the JIRA ticket using the same credentials.

 ##Jira
config.handlers.jira.username = 'jira.scripts'
config.handlers.jira.password = '******'
config.handlers.jira.site     = 'http://jira.aofl.com:8080'
config.handlers.jira.context = ''
config.handlers.jira.format = 'one-line'

**Comment by esigler** [comment]
@jsandova Based on that URL, it seems like you might need to set [`use_ssl`](https://github.com/esigler/lita-jira#optional-attributes) to `true`?

**Comment by jsandova** [comment]
Whenever I add config.handlers.jira.use_ssl = true to the config my lita chat bot will not start up.

**Comment by jsandova** [comment]
I have tried it with config.handlers.jira.use_ssl = false as well and the lita chat bot still doesn't start up.

**Comment by esigler** [comment]
Hmm - this is with lita-jira [0.8.0](https://github.com/esigler/lita-jira/releases/tag/v0.8.0) released 6 days ago?  If Lita isn't starting up with that config item set, can you provide the error message?

**Comment by jsandova** [comment]
I just ran gem install again to make sure and it looks like I didn't have the latest version. Even with lita-jira 0.8.0 installed it will not start up with that config added. Where are error messages logged to?

root@bot:/home/roboto# sudo gem install "lita-jira"
Fetching: lita-jira-0.8.0.gem (100%)
Successfully installed lita-jira-0.8.0
Parsing documentation for lita-jira-0.8.0
Installing ri documentation for lita-jira-0.8.0
Done installing documentation for lita-jira after 0 seconds
1 gem installed

**Comment by esigler** [comment]
My apologies, I wasn't more specific - I'm looking for the error messages that are on the STDOUT / console when you start Lita.  There should be something when you run `bundle exec lita` like:

```
[2016-03-04 06:32:15 UTC] FATAL: Lita configuration file could not be processed. The exception was:
...
```

Also, try removing the configuration item `config.handlers.jira.format` temporarily and let me know if that works for you.

**Comment by jsandova** [comment]
Here is the output.

root@bot:/home/roboto# [2016-03-04 17:37:05 UTC] FATAL: Lita configuration file could not be processed. The exception was:
undefined method `use_ssl=' for #<Lita::Configuration:0x000000044cae88>
Full backtrace:
/home/roboto/lita_config.rb:68:in `block in <top (required)>'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/registry.rb:17:in `configure'
/home/roboto/lita_config.rb:1:in `<top (required)>'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/configuration_builder.rb:49:in `load'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/configuration_builder.rb:49:in `load_user_config'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita.rb:75:in `run'
/var/lib/gems/2.2.0/gems/lita-4.7.0/lib/lita/cli.rb:77:in `start'
/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/var/lib/gems/2.2.0/gems/lita-4.7.0/bin/lita:6:in `<top (required)>'
/usr/local/bin/lita:23:in `load'
/usr/local/bin/lita:23:in `<main>'
